input-files:
  - ./pandoc/title.yaml
  - ./chapter-00/chapter-00.md
  - ./chapter-01/chapter-01.md
  - ./chapter-02/chapter-02.md
  - ./chapter-03/chapter-03.md
  - ./chapter-04/chapter-04.md
  - ./chapter-05/chapter-05.md
  - ./chapter-06/chapter-06.md
  - ./chapter-07/chapter-07.md
  - ./chapter-08/chapter-08.md
  - ./chapter-09/chapter-09.md
  - ./chapter-10/chapter-10.md
  - ./chapter-11/chapter-11.md
  - ./chapter-12/chapter-12.md
  - ./chapter-13/chapter-13.md
  - ./chapter-13/chapter-13.md
  - ./chapter-14/chapter-14.md
  - ./chapter-15/chapter-15.md
  - ./chapter-16/chapter-16.md
  - ./chapter-17/chapter-17.md
  - ./appendix-01/appendix-01.md
  - ./appendix-02/appendix-02.md
epub-cover-image: pandoc/cover.png
filters:
   - ./pandoc/filter.lua
resource-path:
  - .
  - chapter-00
  - chapter-01
  - chapter-02
  - chapter-03
  - chapter-04
  - chapter-05
  - chapter-06
  - chapter-07
  - chapter-08
  - chapter-09
  - chapter-10
  - chapter-11
  - chapter-12
  - chapter-13
  - chapter-14
  - chapter-15  
  - chapter-16
  - chapter-17
  - appendix-01
  - appendix-02
toc: true
output-file: vulkanbook.epub
