name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 23 for x64
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: 23
          architecture: x64
      
      - name: Build with Maven
        working-directory: booksamples
        run: mvn --batch-mode --update-snapshots clean package

      - name: Generate PDF with Pandoc
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/bookcontents:/data \
            pandoc/extra:latest \
            $FILES -d ./pandoc/settings.yaml
        env:
          FILES: ${{ env.FILES }}

      - name: Commit and push generated PDF
        working-directory: bookcontents
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add vulkanbook.epub
          git commit -m "Add generated EPUIB: vulkanbook.epub" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}